#!/usr/bin/python3
"""Factorize as many numbers as possible
into a product of two smaller numbers.
"""
import sys

with open(sys.argv[1], "r") as my_file:
    Lines = my_file.readlines()
    new_Lines = [int(i) for i in Lines]
    new_Lines.sort()

    for line in new_Lines:
        a = 2
        while line > 2:
            if line % a == 0:
                p = line // a
                print("{}={}*{}".format(line, p, a))
                break
            else:
                a += 1
