#!/usr/bin/python3
"""find these two primes p and q of given n, n = p x q"""
import sys
from math import ceil, sqrt

with open(sys.argv[1], "r") as my_file:
    n = int(my_file.readline())
    # check if value is even
    if n % 2 == 0:
        print("{}={}*{}".format(n, int(n / 2), 2))
    # value is a odd/prime number
    else:
        k = int(ceil(sqrt(n)))
        is_prime = True
        while is_prime:
            x = k * k - n
            s = int(sqrt(x))
            if(s * s == x):
                is_prime = False
            else:
                k += 1
        print("{}={}*{}".format(n, k + s, k - s))
